resources:
  - namespace.yaml
helmCharts:
  - name: falco
    repo: https://falcosecurity.github.io/charts
    version: 1.17.1
    releaseName: falco
    namespace: falco
    valuesFile: falco-values.yaml
patchesJson6902:
  - target:
      version: v1
      kind: ServiceAccount
      name: falco-falcosidekick
    patch: |-
      - op: add
        path: "/metadata/annotations"
        value:
          iam.gke.io/gcp-service-account: falco-sidekick@${PROJECT_ID}.iam.gserviceaccount.com
