  apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
  kind: PubSubTopic
  metadata:
    namespace: config-control
    labels:
      label-one: "falco-sidekick"
    name: falco-security-alerts
  spec:
    resourceID: falco-security-alerts
---
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubSubscription
metadata:
  namespace: config-control
  name: falco-alerts-subscription
spec:
  retainAckedMessages: false
  ackDeadlineSeconds: 15
  messageRetentionDuration: 86400s
  topicRef:
    name: falco-security-alerts
---