apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubFeature
metadata:
  name: gke-config-management
  namespace: config-control
spec:
  projectRef:
    external: ${PROJECT_ID} # kpt-set: ${PROJECT_ID}
  location: global
  # The resourceID must be "configmanagement" if you want to use Anthos config
  # management feature.
  resourceID: configmanagement
---
apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubMembership
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: ${PROJECT_ID} # kpt-set: ${PROJECT_ID}
  name: gke-hub-membership
  namespace: config-control
spec:
  location: global
  authority:
    # Issuer must contain a link to a valid JWT issuer. Your ContainerCluster is one.
    issuer: https://container.googleapis.com/v1/projects/${PROJECT_ID}/locations/northamerica-northeast1/clusters/falco-sidekick # kpt-set: https://container.googleapis.com/v1/projects/${PROJECT_ID}/locations/northamerica-northeast1/clusters/falco-sidekick
  description: A sample GKE Hub membership
  endpoint:
    gkeCluster:
      resourceRef:
        name: falco-sidekick
---
apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubFeatureMembership
metadata:
  name: gke-config-management
  namespace: config-control
spec:
  projectRef:
    external: ${PROJECT_ID} # kpt-set: ${PROJECT_ID}
  location: global
  membershipRef:
    name: gke-hub-membership
  featureRef:
    name: gke-config-management
  configmanagement:
    configSync:
      sourceFormat: unstructured
      git:
        policyDir: deploy
        gcpServiceAccountRef:
          external: config-sync-sa@${PROJECT_ID}.iam.gserviceaccount.com # kpt-set: config-sync-sa@${PROJECT_ID}.iam.gserviceaccount.com
        secretType: gcpserviceaccount
        syncBranch: master
        syncRepo: https://source.developers.google.com/p/${PROJECT_ID}/r/falco-sidekick # kpt-set: https://source.developers.google.com/p/${PROJECT_ID}/r/falco-sidekick
    policyController:
      enabled: true
      referentialRulesEnabled: true
      logDeniesEnabled: true
      templateLibraryInstalled: true
      auditIntervalSeconds: "20"
    binauthz:
      enabled: true
    hierarchyController:
      enabled: true
      enablePodTreeLabels: true
      enableHierarchicalResourceQuota: true